<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 1 Sprint 2 Assignment 1*

# Apply the t-test to real data

Your assignment is to determine which issues have "statistically significant" differences between political parties in this [1980s congressional voting data](https://archive.ics.uci.edu/ml/datasets/Congressional+Voting+Records). The data consists of 435 instances (one for each congressperson), a class (democrat or republican), and 16 binary attributes (yes or no for voting for or against certain issues). Be aware - there are missing values!

Your goals:

1. Load and clean the data (or determine the best method to drop observations when running tests)
2. Using hypothesis testing, find an issue that democrats support more than republicans with p < 0.01
3. Using hypothesis testing, find an issue that republicans support more than democrats with p < 0.01
4. Using hypothesis testing, find an issue where the difference between republicans and democrats has p > 0.1 (i.e. there may not be much of a difference)

Note that this data will involve *2 sample* t-tests, because you're comparing averages across two groups (republicans and democrats) rather than a single group against a null hypothesis.

Stretch goals:

1. Refactor your code into functions so it's easy to rerun with arbitrary variables
2. Apply hypothesis testing to your personal project data (for the purposes of this notebook you can type a summary of the hypothesis you formed and tested)

In [0]:
### YOUR CODE STARTS HERE

In [0]:
import pandas as pd
from scipy.stats import ttest_ind

In [30]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data

--2020-01-30 01:13:19--  https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18171 (18K) [application/x-httpd-php]
Saving to: ‘house-votes-84.data.1’

house-votes-84.data 100%[===================>]  17.75K  --.-KB/s    in 0.06s

2020-01-30 01:13:19 (277 KB/s) - ‘house-votes-84.data.1’ saved [18171/18171]

In [31]:
column_headers = ['party','handicapped-infants','water-project',
                          'budget','physician-fee-freeze', 'el-salvador-aid',
                          'religious-groups','anti-satellite-ban',
                          'aid-to-contras','mx-missile','immigration',
                          'synfuels', 'education', 'right-to-sue','crime','duty-free',
                          'south-africa']

df = pd.read_csv('house-votes-84.data', 
                 header=None, 
                 names=column_headers,
                 na_values="?")

df.head()

        party handicapped-infants water-project  ... crime duty-free south-africa
0  republican                   n             y  ...     y         n            y
1  republican                   n             y  ...     y         n          NaN
2    democrat                 NaN             y  ...     y         n            n
3    democrat                   n             y  ...     n         n            y
4    democrat                   y             y  ...     y         y            y

[5 rows x 17 columns]

In [0]:
# I had already completed the assignment when chrome closed, shot an error message, and deleted everything.
# so your not going to make me feel bad over a little copy pasting

In [32]:
df = df.replace({'y': 1, 'n': 0})
df.head()

        party  handicapped-infants  ...  duty-free  south-africa
0  republican                  0.0  ...        0.0           1.0
1  republican                  0.0  ...        0.0           NaN
2    democrat                  NaN  ...        0.0           0.0
3    democrat                  0.0  ...        0.0           1.0
4    democrat                  1.0  ...        1.0           1.0

[5 rows x 17 columns]

In [33]:
rep = df[df['party']=='republican']
rep.head()

         party  handicapped-infants  ...  duty-free  south-africa
0   republican                  0.0  ...        0.0           1.0
1   republican                  0.0  ...        0.0           NaN
7   republican                  0.0  ...        NaN           1.0
8   republican                  0.0  ...        0.0           1.0
10  republican                  0.0  ...        0.0           0.0

[5 rows x 17 columns]

In [34]:
dem = df[df['party']=='democrat']
dem.head()

      party  handicapped-infants  water-project  ...  crime  duty-free  south-africa
2  democrat                  NaN            1.0  ...    1.0        0.0           0.0
3  democrat                  0.0            1.0  ...    0.0        0.0           1.0
4  democrat                  1.0            1.0  ...    1.0        1.0           1.0
5  democrat                  0.0            1.0  ...    1.0        1.0           1.0
6  democrat                  0.0            1.0  ...    1.0        1.0           1.0

[5 rows x 17 columns]

In [0]:
# Now for my code

In [0]:
def tt_ind_df( left_dataframe, right_dataframe, shared_columns_list):
  for item in shared_columns_list:
    print(item)
    print('{:.10f}'.format(ttest_ind(left_dataframe[item], right_dataframe[item], nan_policy='omit').pvalue))

In [0]:
# So this was facinating. although everything I wrote was deleted, the function
# I created was still remembered. So I was able to import inspect to get the source
# code and recreate it relatively easily. Slightly less pissed now

In [46]:
tt_ind_df(rep, dem, ['handicapped-infants','water-project','budget','physician-fee-freeze',
                     'el-salvador-aid','religious-groups','anti-satellite-ban','aid-to-contras',
                     'mx-missile','immigration','synfuels', 'education', 'right-to-sue',
                     'crime','duty-free','south-africa'])

handicapped-infants
0.0000000000
water-project
0.9291556824
budget
0.0000000000
physician-fee-freeze
0.0000000000
el-salvador-aid
0.0000000000
religious-groups
0.0000000000
anti-satellite-ban
0.0000000000
aid-to-contras
0.0000000000
mx-missile
0.0000000000
immigration
0.0833024849
synfuels
0.0000000000
education
0.0000000000
right-to-sue
0.0000000000
crime
0.0000000000
duty-free
0.0000000000
south-africa
0.0000000000

In [0]:
# So Im doing this somewhat backwards, yell at me later if you want.
# obvious points of similarity though are on 'water-project' and 'immigration'
# 'water-project' easily qualifies for assignment goal 4

In [0]:
def mean_diff_df( left_dataframe, right_dataframe, shared_columns_list):
  for item in shared_columns_list:
    print(item)
    print(left_dataframe[item].mean() - right_dataframe[item].mean())

In [51]:
mean_diff_df(rep, dem, ['handicapped-infants','water-project','budget','physician-fee-freeze',
                        'el-salvador-aid','religious-groups','anti-satellite-ban','aid-to-contras',
                        'mx-missile','immigration','synfuels', 'education', 'right-to-sue',
                        'crime','duty-free','south-africa'])

handicapped-infants
-0.41677237491190977
water-project
0.0046647065475518
budget
-0.7543151969981238
physician-fee-freeze
0.9338247338247339
el-salvador-aid
0.7358288770053476
religious-groups
0.42084617539927144
anti-satellite-ban
-0.5314600314600315
aid-to-contras
-0.6760310963648253
mx-missile
-0.6429130009775171
immigration
0.08609286784191733
synfuels
-0.37380688124306327
education
0.7263894286824718
right-to-sue
0.5710769539883465
crime
0.6311719070981463
duty-free
-0.5477066094595975
south-africa
-0.2776008885597927

In [0]:
# Because rep is in the left of the function, if the output
# is positive republicans support it more. If negative then
# democrats support it more

# and because we know only 'water-project' and 'immigration' are the only
# answers that can't be used, simply finding one of the
# others for each resolves the goals

# and they are:
# 'physician-fee-freeze' for republicans
# 'duty-free' for democrats
# Yes, I basically picked at random